### ISSUE TITLE
Requirement for php-mysql

### ISSUE THREAD

**Issue by dgaussin** [trilbymedia/grav-plugin-tntsearch#8]
Got an issue when installing the plugin on server.

`Undefined class constant 'PDO::MYSQL_ATTR_USE_BUFFERED_QUERY' in user/plugins/tntsearch/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:184`

Solved installing the php-mysql extension but seems weird for a sqlite3 plugin.

**Comment by rhukster** [comment]
This is basically because the TNTSearch Indexer actually supports pulling its search content directly from Mysql.  We don't use this, and it's local store is Sqlite, but just because it can, it reference classes and constants that are part of that mysql package. Ideally they would break out these different platforms into separate classes (that we would not ever use) but unfortunately it's all in the one class. You could raise an issue on the tntsearch repo?
